version: 2
jobs:
  test:
    docker:
      - image: circleci/node:lts-jessie
    steps:
      - checkout
      - run: npm i --verbose
      - run: npm test -- --coverage
      - run: sudo npm i -g codecov
      - run: codecov
      - store_artifacts:
          path: coverage
workflows:
  version: 2
  test-only:
    jobs:
      - test
